/* ============================================================================
   E-COMMERCE DATABASE PROJECT
   File:   01_schema_ddl.sql
   Author: <Your Name>
   Purpose: Creates a fully normalized (3NF) schema for an online store.
            Demonstrates: PK/FK design, CHECK constraints, IDENTITY columns,
            self-referencing FKs (hierarchies), and a 1:M address model.

   RUN ORDER: This is script 1 of 5. Run in order:
   01_schema_ddl.sql -> 02_sample_data.sql -> 03_complex_queries.sql
   -> 04_plsql_programs.sql -> 05_performance_tuning.sql

   Tested against: Oracle Database 19c / 21c / 23ai syntax (IDENTITY columns
   require Oracle 12c Release 1 or later).
   ============================================================================ */

-- Clean slate (safe to ignore ORA-00942 errors if tables don't exist yet)
DROP TABLE inventory_log    CASCADE CONSTRAINTS PURGE;
DROP TABLE reviews          CASCADE CONSTRAINTS PURGE;
DROP TABLE payments         CASCADE CONSTRAINTS PURGE;
DROP TABLE order_items      CASCADE CONSTRAINTS PURGE;
DROP TABLE orders           CASCADE CONSTRAINTS PURGE;
DROP TABLE customer_addresses CASCADE CONSTRAINTS PURGE;
DROP TABLE products         CASCADE CONSTRAINTS PURGE;
DROP TABLE employees        CASCADE CONSTRAINTS PURGE;
DROP TABLE suppliers        CASCADE CONSTRAINTS PURGE;
DROP TABLE categories       CASCADE CONSTRAINTS PURGE;
DROP TABLE customers        CASCADE CONSTRAINTS PURGE;

-- ----------------------------------------------------------------------------
-- 1. CUSTOMERS
-- ----------------------------------------------------------------------------
CREATE TABLE customers (
    customer_id      NUMBER         GENERATED BY DEFAULT AS IDENTITY
                                     (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    first_name       VARCHAR2(50)   NOT NULL,
    last_name        VARCHAR2(50)   NOT NULL,
    email            VARCHAR2(100)  NOT NULL,
    phone            VARCHAR2(20),
    registration_date DATE          DEFAULT SYSDATE NOT NULL,
    status           VARCHAR2(10)   DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT uq_customers_email   UNIQUE (email),
    CONSTRAINT ck_customers_status  CHECK (status IN ('ACTIVE','INACTIVE'))
);

-- ----------------------------------------------------------------------------
-- 2. CUSTOMER_ADDRESSES  (1 customer -> many addresses; removes repeating
--    address columns from CUSTOMERS, eliminating partial-dependency issues -> 3NF)
-- ----------------------------------------------------------------------------
CREATE TABLE customer_addresses (
    address_id       NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       NUMBER         NOT NULL,
    address_type      VARCHAR2(10)   DEFAULT 'SHIPPING' NOT NULL,
    address_line1     VARCHAR2(100)  NOT NULL,
    address_line2     VARCHAR2(100),
    city              VARCHAR2(50)   NOT NULL,
    state_province    VARCHAR2(50),
    postal_code       VARCHAR2(20),
    country           VARCHAR2(50)   NOT NULL,
    CONSTRAINT fk_addr_customer     FOREIGN KEY (customer_id)
                                     REFERENCES customers(customer_id)
                                     ON DELETE CASCADE,
    CONSTRAINT ck_addr_type         CHECK (address_type IN ('BILLING','SHIPPING'))
);

-- ----------------------------------------------------------------------------
-- 3. CATEGORIES  (self-referencing FK -> supports unlimited category depth,
--    e.g. Electronics -> Laptops -> Gaming Laptops)
-- ----------------------------------------------------------------------------
CREATE TABLE categories (
    category_id       NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name     VARCHAR2(50)   NOT NULL,
    parent_category_id NUMBER,
    CONSTRAINT fk_cat_parent        FOREIGN KEY (parent_category_id)
                                     REFERENCES categories(category_id)
);

-- ----------------------------------------------------------------------------
-- 4. SUPPLIERS
-- ----------------------------------------------------------------------------
CREATE TABLE suppliers (
    supplier_id       NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name     VARCHAR2(100)  NOT NULL,
    contact_email     VARCHAR2(100),
    phone             VARCHAR2(20),
    country           VARCHAR2(50)
);

-- ----------------------------------------------------------------------------
-- 5. PRODUCTS
-- ----------------------------------------------------------------------------
CREATE TABLE products (
    product_id        NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name       VARCHAR2(100)  NOT NULL,
    category_id        NUMBER         NOT NULL,
    supplier_id        NUMBER         NOT NULL,
    unit_price         NUMBER(10,2)   NOT NULL,
    stock_quantity      NUMBER         DEFAULT 0 NOT NULL,
    created_date        DATE           DEFAULT SYSDATE NOT NULL,
    is_active           CHAR(1)        DEFAULT 'Y' NOT NULL,
    CONSTRAINT fk_prod_category     FOREIGN KEY (category_id)  REFERENCES categories(category_id),
    CONSTRAINT fk_prod_supplier     FOREIGN KEY (supplier_id)  REFERENCES suppliers(supplier_id),
    CONSTRAINT ck_prod_price        CHECK (unit_price >= 0),
    CONSTRAINT ck_prod_stock        CHECK (stock_quantity >= 0),
    CONSTRAINT ck_prod_active       CHECK (is_active IN ('Y','N'))
);

-- ----------------------------------------------------------------------------
-- 6. EMPLOYEES  (self-referencing FK -> manager hierarchy)
-- ----------------------------------------------------------------------------
CREATE TABLE employees (
    employee_id        NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          VARCHAR2(50)   NOT NULL,
    last_name            VARCHAR2(50)   NOT NULL,
    hire_date             DATE           DEFAULT SYSDATE NOT NULL,
    salary                NUMBER(10,2)   NOT NULL,
    department            VARCHAR2(30),
    manager_id            NUMBER,
    CONSTRAINT fk_emp_manager        FOREIGN KEY (manager_id) REFERENCES employees(employee_id),
    CONSTRAINT ck_emp_salary         CHECK (salary > 0)
);

-- ----------------------------------------------------------------------------
-- 7. ORDERS
-- ----------------------------------------------------------------------------
CREATE TABLE orders (
    order_id              NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id            NUMBER         NOT NULL,
    employee_id            NUMBER,
    shipping_address_id    NUMBER         NOT NULL,
    order_date              DATE           DEFAULT SYSDATE NOT NULL,
    status                   VARCHAR2(15)   DEFAULT 'PENDING' NOT NULL,
    total_amount            NUMBER(10,2)   DEFAULT 0 NOT NULL,
    CONSTRAINT fk_ord_customer       FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT fk_ord_employee       FOREIGN KEY (employee_id) REFERENCES employees(employee_id),
    CONSTRAINT fk_ord_address        FOREIGN KEY (shipping_address_id) REFERENCES customer_addresses(address_id),
    CONSTRAINT ck_ord_status         CHECK (status IN ('PENDING','PROCESSING','SHIPPED','DELIVERED','CANCELLED')),
    CONSTRAINT ck_ord_total          CHECK (total_amount >= 0)
);

-- ----------------------------------------------------------------------------
-- 8. ORDER_ITEMS  (resolves the M:M between ORDERS and PRODUCTS)
-- ----------------------------------------------------------------------------
CREATE TABLE order_items (
    order_item_id          NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                NUMBER         NOT NULL,
    product_id              NUMBER         NOT NULL,
    quantity                  NUMBER         NOT NULL,
    unit_price                NUMBER(10,2)   NOT NULL,
    line_total                NUMBER(10,2)   GENERATED ALWAYS AS (quantity * unit_price),
    CONSTRAINT fk_oi_order            FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    CONSTRAINT fk_oi_product          FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT ck_oi_qty               CHECK (quantity > 0)
);

-- ----------------------------------------------------------------------------
-- 9. PAYMENTS
-- ----------------------------------------------------------------------------
CREATE TABLE payments (
    payment_id              NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                  NUMBER         NOT NULL,
    payment_date               DATE           DEFAULT SYSDATE NOT NULL,
    amount                     NUMBER(10,2)   NOT NULL,
    payment_method             VARCHAR2(20)   NOT NULL,
    payment_status              VARCHAR2(15)   DEFAULT 'PENDING' NOT NULL,
    CONSTRAINT fk_pay_order             FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT ck_pay_method             CHECK (payment_method IN ('CREDIT_CARD','DEBIT_CARD','PAYPAL','BANK_TRANSFER','COD')),
    CONSTRAINT ck_pay_status              CHECK (payment_status IN ('PENDING','COMPLETED','FAILED','REFUNDED'))
);

-- ----------------------------------------------------------------------------
-- 10. REVIEWS
-- ----------------------------------------------------------------------------
CREATE TABLE reviews (
    review_id                NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id                 NUMBER         NOT NULL,
    customer_id                 NUMBER         NOT NULL,
    rating                       NUMBER(1)      NOT NULL,
    review_comment                VARCHAR2(1000),
    review_date                  DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_rev_product              FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT fk_rev_customer              FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT ck_rev_rating                 CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT uq_rev_one_per_customer        UNIQUE (product_id, customer_id)
);

-- ----------------------------------------------------------------------------
-- 11. INVENTORY_LOG  (audit trail, populated by triggers - see script 04)
-- ----------------------------------------------------------------------------
CREATE TABLE inventory_log (
    log_id                     NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id                   NUMBER         NOT NULL,
    old_quantity                   NUMBER,
    new_quantity                    NUMBER,
    change_qty                       NUMBER,
    change_date                       DATE          DEFAULT SYSDATE NOT NULL,
    reason                              VARCHAR2(100),
    CONSTRAINT fk_log_product                  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

COMMIT;

-- Quick sanity check
SELECT table_name FROM user_tables ORDER BY table_name;
